### ISSUE TITLE
Big list of usability issues / possible enhancements

### ISSUE THREAD

**Issue by dblalock** [mosaicml/composer#194]
This issue exists to capture API subtleties that hurt usability. In order to avoid flooding our list of issues and reduce the friction to reporting them, I'm capturing these (at least initially) here. Empirically, the reduced friction in particular seems to be necessary for me personally to document them. I anticipate the ones we decide to fix will gradually get moved to their own issues.

So far I have:

- [ ] Dataset creation depends on dataloader, which in turn depends on dataset. This is a product of some datasets needing a custom collate function and/or `split_fn`. 
- [ ] Algorithms need state already created, which needs dataloader already created, which makes messing with the dataloader difficult (except in a few targeted ways, like adding another data augmentation)
- [ ] No clean way to create a custom param_group for the optimizer. E.g., for mixture of experts, I want those params to use a lower learning rate.
- [ ] Initialization plumbing is coupled to model and AFAICT hard to change algorithmically. See, e.g., `composer/models/resnets/ImageNet_ResNet::__init__`. Haven't really tried to build it yet, but example use case would be having an algorithm that causes the batchnorms, or a targetted subset thereof, to be initialized differently.
- [x] Hparam subsystem is tightly coupled to core logic, making it difficult to integrate with user's existing hparam management (#269) 
- [ ] Adding a new {dataset, model} takes changes in a number of places / lack of documentation around using a custom dataset without changing composer
- [ ] All-or-nothing choice between using our trainer or manually adding each algorithm. No graceful degradation for, e.g., surgery methods that could in principle work with any trainer.
- [x] Data augmentation algorithms have different functional/standalone APIs. And it's pretty ugly to add them into an existing dataset or dataloader (e.g., `trainloader.dataset.transform.transforms.append(functools.partial(cf.colout, p_row=.1, p_col=.1))`). (moved to #343)
- [ ] Can't get mixup to run by adding to an existing `transforms.Compose` at all.
- [x] Channels_last has no standalone/functional API (moved to #350)
- [ ] Squeeze excite's standalone API prints the network.
- [ ] There's no way to call `batch_colout` because this function isn't imported in `composer/algorithm/colout/__init__.py` and the function `colout` aliases `composer/algorithm/colout/colout.py`
- [ ] #529
- [x] Augmix functional needs a complete docstring
- [ ] Augmix functional API isn't in its method card
- [ ] User has to separately sample a Beta random variable using a helper function for mixup and cutmix functional API. Should probably allow just passing in the beta's parameter (if desired) to the main augmentation function.
- [x] Cutout has no functional API tests (Fixed by #524)
- [ ] #527
- [ ] #526
- [ ] SAM and SWA algorithm names are all caps and get syntax highlighted like a constant in editors
- [ ] Scale schedule has no tests (see #434)
- [ ] #528
- [ ] #525
- [ ] #530
- [ ] Can't run stochastic depth after blurpool because `AttributeError: 'BlurConv2d' object has no attribute 'groups'`.
- [ ] Inconsistent whether `apply` and `match` are documented for algorithms.
- [ ] Event, Logger, and State don't seem to link properly when referenced in parens after arg names in Algorithm apply and match.
- [ ] Inconsistent inclusion of examples before vs after {args, returns, raises} in algorithms directory.
- [ ] Functional API tutorial notebook should (probably?) use transforms for data augmentations, instead of the functional API calls. Or maybe not use augmentations at all?
- [ ] Augmix takes in a mutable list for its augmentation set in most cases, but a string in its Transform version. Should always accept a string or Iterable of Callables, and always default to a string.
- [ ] Factorize module, algo, functional defaults don't all match.
- [ ] One SE module doesn't have the same defaults as everything else
- [X] Cutout should only support fractional length like cutmix
- [ ] We need better input checking + error raising throughout the whole algorithms directory.

*Other augmentations also lack transform wrappers, but can't easily get them since they also rely on seeing the labels.

Planning to check off these off as we either move them to separate issues or decide to wontfix.

**Comment by ravi-mosaicml** [comment]
Moving issue internally to https://www.notion.so/List-of-Usability-Issues-and-Possible-Enhancements-07aef774749c4b2c99aefec06fe685f2
