### ISSUE TITLE
Docs cleanup

### ISSUE THREAD

**Issue by ravi-mosaicml** [mosaicml/composer#480]
- [ ] Pin the sidebar so it automatically scrolls to the currently open page
- [x] Remove documenting of inherited members that don't have new docstrings (addressed in #488)
- [x] Show inheritance and base classes (addressed in #488)
- [x] Ensure that all doctests are passing on jenkins (addressed in #488)
- [ ] Skip documentation of modules that contain no public members

**Comment by ravi-mosaicml** [comment]
Closing for #498 

Not going to address skipping documentation of modules with no public members -- those should be renamed to be private members.
